AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Function to get Synthetic Canary Status

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${AWS::AccountId}-platform-status

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: platformstatus-canary-get
      Description: Return status for myworkplace-login canary.
      Runtime: provided.al2
      Handler: hello.handler
      Code:
        S3Bucket: !Ref S3Bucket.name
        S3Key: bootstrap.zip
      Role: 
      Environment:
        Variables:
          canaryName: myworkplace-login
          canaryRegion: eu-west-2

  ApiGatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: platformstatus

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ResourceId: !Ref ApiGatewayApi.RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: Lambda

  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties: